
name: Flutter CI iOS Working
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: Builds will show in Artifact
          artifacts: "build/ios/iphoneos/app.ipa"
          #path: build/app/outputs/apk/release/app-release.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
