name: Flutter CI iOS Working
on:
  push:
    branches:
      - master

jobs:
  build_iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter pub get
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
#      - name: Upload iPA
#        uses: actions/upload-artifact@master
#        with:
#          name: ios-build
#          path: build/ios/iphoneos
#          path: Users/runner/work/herosAppVikram/herosAppVikram/build/ios/iphoneos/Runner.app

          #      - uses: actions/upload-artifact@v3
          #       - uses: ncipollo/release-action@v1
          #         with:
          #           #path: build/app/outputs/apk/release/app-release.apk
          #           path: build/ios/iphoneos
          #           artifacts: "build/ios/iphoneos/app.ipa"
          #           tag: v1.0.${{ github.run_number }}
          #           token: ${{ secrets.TOKEN }}

  iOS_FireBase:
    #     name: Upload iOS to Firebase
    needs: [build_iOS]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #     - name: Download Artifact
      #       uses: actions/download-artifact@master
      #       with:
      #         name: ios-build
      - name: Upload iPA Artifact to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_IOS}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          group: testers
          file: build/ios/iphoneos
#          file: Users/runner/work/herosAppVikram/herosAppVikram/build/ios/iphoneos/Runner.ipa
#          file: Runner.ipa



  # name: Flutter CI Android Working
  build_APK_FireBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - run: flutter pub get
      - run: flutter build apk --debug

      #      - uses: actions/upload-artifact@v1
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/debug/app-debug.apk"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}

      - name: Upload APK Artifact to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          group: testers
          file: build/app/outputs/apk/debug/app-debug.apk
#          releaseNotes: v1.0.0
#          releaseNotesFile: v1.0.0

